### ISSUE TITLE
Checkout functionality

### ISSUE THREAD

**Issue by ksumm** [ksumm/the_Bloom_PP5#12]
As a **Site User** I want to be able to **complete the checkout process** for my shopping cart so that I can pay for the order

**Acceptance criteria:** 
Given that I’ve added all the items to my cart and I’m logged in,
When I click the check out button,
Then the checkout page loads with all my payment and shipping information preloaded.

**Tasks:**
 - [x] Create checkout app and order models.
 - [x] Create a checkout page that displays cart's content
 - [x] Implement a form to collect and validate user's billing and delivery information
 - [x] Implement the logic to determine the delivery cost based on the amount spent.
 - [x] Implement the logic to calculate the order total.
