### ISSUE TITLE
Remove products from shopping bag

### ISSUE THREAD

**Issue by ksumm** [ksumm/the_Bloom_PP5#13]
As a  **Site User,** I want to **remove products from my shopping bag** so that I can adjust my order before making a purchase.

**Acceptance criteria:**
Given I am a logged-in user and I have added products to my cart, When I click on the "Remove" button for a product, Then the product should be removed from my cart.

**Tasks:** 
 - [x]  implement the Remove button for each product to the "Shopping Bag" page
 - [x] implement the logic to remove products from the user's cart when they click "Remove."
 - [x] implement the logic to update the cart's total price when products are removed
 - [x] implement the "Success" message displaying after the product was deleted
