### ISSUE TITLE
Newsletter Signup

### ISSUE THREAD

**Issue by ksumm** [ksumm/the_Bloom_PP5#14]
As a **Site User** user, I want to **sign up for newsletters on the website** so that I can keep up with updates and deals.

**Acceptance criteria:**
 - Given I am a user, When I visit the website, Then I should have an option to subscribe to newsletters.
 - Given I am a user, When I submit the newsletter subscribe form, Then I should receive the confirmation message.

**Tasks:**
 - [x] Register an account on Mailchimp website.
 - [x] Add the code to the footer
 - [x] Test if the form works correctly
