### ISSUE TITLE
Website Footer

### ISSUE THREAD

**Issue by ksumm** [ksumm/the_Bloom_PP5#15]
As a **Site User** I want to **access the footer of the website**,  so that I can visit the site's social media pages

** Acceptance Criteria **

 - Footer must redirect user to relevant social media and information pages
 - Footer should be responsive to all device sizes
 - Footer should have newsletter subscription
 
** Tasks **

- [x] Design the Footer
- [x] Add link to the Facebook page
- [x] Add copyright statement
- [x] Add a newsletter subscription
